### ISSUE TITLE
Where is nice calendar dots?

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-days#7]
During the one of previous plugin releases the nice calendar dots were replaced by task names:
<img width="354" alt="CleanShot 2023-07-16 at 19 43 14@2x" src="https://github.com/sethyuan/logseq-plugin-days/assets/1984175/0901e270-45fd-4d6c-a52d-986e755479a9">

It looks awful. How can I disable this and return to dots only mode?

Note: these tasks are periodic

**Comment by sethyuan** [comment]
The dots are still there, a dot means that you have reference of the current page in that day (you have to go in a page to see it if you're using a dynamic calendar, that is, one with a `*`).

The new release added a feature to display SCHEDULED and DEADLINE to the calendar as special dates, that's why you're seeing these. I think I can add support for a block property that controls whether or not you want to display a particular SCHEDULED / DEADLINE in the calendar, then you can use this property on those blocks you don't want to be displayed in the calendar.

**Comment by stdword** [comment]
Oh, yes, I've mixed up dots and tasks.

It would be very nice to have a global setting to disable displaying of all DEADLINE & SCHEDULED tasks 🙏

**Comment by sethyuan** [comment]
A setting for this is implemented in a new version, please have a try.

**Comment by stdword** [comment]
Nice! It works! Thank you 🙏
